version: '3.2'
services:
    redis:
        image: redis:alpine
        volumes:
            - ./redis-data:/data
        restart: always
        networks:
            - axum-network
    postgres:
        image: postgres:alpine
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=88888888
            - POSTGRES_DB=axumdb3
        restart: always
        networks:
            - axum-network
        ports:
            - '5433:5432'
    axum:
        build: .
        ports:
            - '80:3000'
        env_file:
            - .env
        networks:
            - axum-network
        depends_on:
            - redis
            - postgres
networks:
    axum-network:
        driver: bridge
