version: '3.2'
services:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./redis-data:/data
        restart: always
        networks:
            - axum-network
    postgres:
        image: postgres:alpine
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=88888888
            - POSTGRES_DB=axumdb3
        restart: always
        networks:
            - axum-network
    axum:
        build: .
        ports:
            - 3000:3000
        environment:
            - DATABASE_URL=postgresql://postgres:88888888@localhost:5432/axumdb3?schema=public
        networks:
            - axum-network
networks:
    axum-network:
        driver: bridge
